

# Файл локализации, используемый в плагине
locale: default

# Имя мира, где должен работать плагин
world: world

# Максимальное количество игроков, которое может находиться в одной битве
max_players: 3

# Расстояние в блоках, которое должно быть между игроками, чтобы началась дуэль
distance_between_players: 5

# Количество секунд, сколько времени можно будет принять вызов, после его отправки
duration_request: 20

# Количество секунд, сколько игроку нужно ждать, чтобы отправить новый вызов одному и тому же игроку
duration_between_request: 30

# Количество секунд, сколько длится голосование за набор дуэли
duration_polling: 20